### ISSUE TITLE
Deprecation warning for pip

### ISSUE THREAD

**Issue by gui11aume** [cellcomplexitylab/themisto#9]
Running `docker build -t themisto:1.0 .` issues a deprecation warning.

    WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
    Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
    To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

The `pip3` commands should be updated according to these instructions.

**Comment by yipryan2** [comment]
Submitted a new pull request on fixing deprecation warning for pip.
